ALTER TABLE Products ALTER COLUMN product_id SMALLINT NOT NULL;
ALTER TABLE Products ADD PRIMARY KEY (product_id);

ALTER TABLE Customers ALTER COLUMN customer_id INT NOT NULL;
ALTER TABLE Customers ADD PRIMARY KEY (customer_id);

ALTER TABLE Stores ALTER COLUMN store_id INT NOT NULL;
ALTER TABLE Stores ADD PRIMARY KEY (store_id);

ALTER TABLE Region ALTER COLUMN region_id TINYINT NOT NULL;
ALTER TABLE Region ADD PRIMARY KEY (region_id);